[package]
name = "hal"
version = "0.0.0"
authors = ["Steven Roose <steven@stevenroose.org>"]
license = "CC0-1.0"
homepage = "https://github.com/stevenroose/hal/"
repository = "https://github.com/stevenroose/hal/"
description = "hal - the Bitcoin companion"
keywords = [ "crypto", "bitcoin" ]
readme = "README.md"

[lib]
name = "hal"
path = "src/lib.rs"

[[bin]]
name = "hal"
path = "src/main.rs"

[dependencies]
clap = "2.32"
log = "0.4.5"
fern = "0.5.6"

serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.34"
hex = "0.3.2"

bitcoin = { version = "0.15", features = [ "serde-decimal" ] }
bitcoin-bech32 = "0.8.0"
secp256k1 = "0.11"

[patch."crates-io"]
bitcoin = { git = "https://github.com/stevenroose/rust-bitcoin.git", branch = "devel" }
